[server]
maxUploadSize = 5
enableXsrfProtection=false # IMPORTANTE FALLO STREAMLIT ELIMINAR CUANDO SEA CORREGIDO
[theme]
primaryColor="#F63366"
backgroundColor="#edf2f4"
secondaryBackgroundColor="#1d3557"
textColor="#2b2d42"
font="monospace"
